"""empty message

Revision ID: 315d20f83702
Revises: 0161689933cb
Create Date: 2019-05-25 14:03:34.603620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '315d20f83702'
down_revision = '0161689933cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('out_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.drop_index('token', table_name='usertoken')
    op.drop_table('usertoken')
    op.create_unique_constraint(None, 'article', ['title'])
    op.create_unique_constraint(None, 'kind', ['name'])
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'kind', type_='unique')
    op.drop_constraint(None, 'article', type_='unique')
    op.create_table('usertoken',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('out_time', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('token', 'usertoken', ['token'], unique=True)
    op.drop_table('user_token')
    # ### end Alembic commands ###
