"""empty message

Revision ID: ea7e6f1549b4
Revises: b642ee155062
Create Date: 2019-05-19 16:19:15.784639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7e6f1549b4'
down_revision = 'b642ee155062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('imags', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'imags')
    # ### end Alembic commands ###
